version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:Mc33zetJFUQe3LaXtCNHJkz095iPIUshGbEfh52cDEs=
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=api-laravel
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: api-laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
